name: 'auth-logic-trigger CI/CD'

env:
  SOURCE_PATH: './src/auth-logic-trigger/Service/Service.CoreApi'
  AZURE_WEBAPP_NAME: 'api-dd-logicapp-int'  
  AZURE_WEBAPP_PACKAGE_PATH: './auth-logic-trigger/release'
  DOTNET_VERSION: '6.0.202'  

on:    
  pull_request:
    branches: [ main ]
    paths:
      - './src/auth-logic-trigger'
      - './github/workflows/auth-logic-trigger.yml'
  workflow_dispatch: 
jobs:  
  build:    
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Azure CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:          
          inlineScript: |
            az webapp list -o table

      - name: Install dependencies
        run: |
          cd ${{ env.SOURCE_PATH }}
          dotnet restore          
      
      - name: Build and Publish
        run: |
          cd ${{ env.SOURCE_PATH }}         
          dotnet build --configuration Release --no-restore
          dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      
      - uses: azure/webapps-deploy@v2
        name: Deploy
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}          
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
  
          